packages:
  - packages/swrv
  - packages/site

catalog:
  "@playwright/test": 1.59.1
  "@types/node": 24.12.2
  "@vue/server-renderer": 3.5.32
  bumpp: 11.0.1
  dequal: 2.0.3
  esbuild: 0.28.0
  jsdom: 29.0.2
  oxc-minify: 0.127.0
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitepress: 2.0.0-alpha.17
  vitepress-plugin-npm-commands: 0.10.0
  vitepress-plugin-tabs: 0.9.0
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: 3.5.32

catalogMode: prefer
overrides:
  vue: "catalog:"
  "@vue/server-renderer": "catalog:"
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
