packages:
  - packages/swrv
  - packages/site

catalog:
  "@playwright/test": 1.61.1
  "@types/node": 24.13.2
  "@vue/server-renderer": 3.5.39
  bumpp: 11.1.0
  dequal: 2.0.3
  esbuild: 0.28.1
  jsdom: 29.1.1
  oxc-minify: 0.138.0
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1
  vitepress: 2.0.0-alpha.17
  vitepress-plugin-npm-commands: 0.10.0
  vitepress-plugin-tabs: 0.9.0
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  vue: 3.5.39

catalogMode: prefer
allowBuilds:
  esbuild: true
overrides:
  vue: "catalog:"
  "@vue/server-renderer": "catalog:"
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
